#[derive(Debug, Clone)]
pub enum Node {
    VarLDecl { name: String, value: Box<Node> },
    VarGDecl { name: String, value: Box<Node> },
    ConstDecl { name: String, value: Box<Node> },
    UpdateDecl { name: String, value: Box<Node> },
    MultiVarL { names: Vec<String>, values: Vec<Box<Node>> },
    UpdateIndex { name: String, index: Box<Node>, value: Box<Node> },
    Summon(String),
    VarAccess(String),
    Print(Box<Node>),
    InputExpr(Box<Node>),
    TypeOf(Box<Node>),
    ToInt(Box<Node>),
    ToFloat(Box<Node>),
    ToString(Box<Node>),
    ToBool(Box<Node>),
    Integer(i64),
    Float(f64),
    StringLit(String),
    Boolean(bool),
    Null,
    Array(Vec<Node>),
    IndexAccess { name: String, index: Box<Node> },
    MethodCall { object: String, method: String, args: Vec<Node> },
    MathCall { method: String, args: Vec<Node> },
    FileCall { method: String, args: Vec<Node> },
    BinaryOp { left: Box<Node>, op: String, right: Box<Node> },
    UnaryOp { op: String, operand: Box<Node> },
    Check {
        condition: Box<Node>,
        body: Vec<Node>,
        or_checks: Vec<(Node, Vec<Node>)>,
        else_body: Option<Vec<Node>>,
    },
    Circle { name: String, count: Box<Node>, body: Vec<Node> },
    Shatter,
    Skip,
    FuncDecl { name: String, func_type: String, params: Vec<String>, body: Vec<Node> },
    FuncCall { name: String, args: Vec<Node> },
    Reply(Box<Node>),
    Rest(Box<Node>),
    Wait(Box<Node>),
    TriggerCall { name: String, trigger_type: String, value: Box<Node> },
    Guard { condition: Box<Node>, body: Vec<Node> },
    UseModule(String),
    MapLit { keys: Vec<String>, values: Vec<Box<Node>> },
    Attempt {
        body: Vec<Node>,
        rescue_param: Option<String>,
        rescue_body: Option<Vec<Node>>,
        always_body: Option<Vec<Node>>,
    },
    JsonCall { method: String, args: Vec<Node> },
    DateCall { method: String, args: Vec<Node> },
    SystemCall { method: String, args: Vec<Node> },
    HttpCall { method: String, args: Vec<Node> },
    CryptoCall { method: String, args: Vec<Node> },
    AsyncBlock { body: Vec<Node> },
    Protect { vars: Vec<String>, body: Vec<Node> },
}